export const SHUFFLE = 'SHUFFLE'
export const DRAW_TWO = 'DRAW_TWO'
export const USER_DRAW_ONE = 'USER_DRAW_ONE'
export const DEALER_DRAW_ONE = 'DEALER_DRAW_ONE'
export const CREATE_USER = 'CREATE_USER' 
export const WINNING_HAND = 'WINNING_HAND' 
export const PAY_BLACKJACK = 'PAY_BLACKJACK' 